FROM golang:latest
RUN apt-get -qq update
RUN git clone https://gist.github.com/kenzo0107/e4350b16fc0648e1303b helloworld
#WORKDIR /bin/helloworld
#RUN go build -o main .
#CMD ["/bin/helloworld/main"]


